"""3 migration

Revision ID: 30b778b5773e
Revises: 324440f9948c
Create Date: 2022-06-16 23:06:46.695192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b778b5773e'
down_revision = '324440f9948c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
