"""Second migration

Revision ID: 324440f9948c
Revises: d096e80d0c27
Create Date: 2022-06-16 20:58:37.586705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324440f9948c'
down_revision = 'd096e80d0c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
