"""5 migration

Revision ID: 62632de77ad3
Revises: b7fc63d49e9b
Create Date: 2022-06-16 23:09:21.416764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62632de77ad3'
down_revision = 'b7fc63d49e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
