"""4 migration

Revision ID: b7fc63d49e9b
Revises: 30b778b5773e
Create Date: 2022-06-16 23:07:51.488946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fc63d49e9b'
down_revision = '30b778b5773e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
